-- Nook M3-1 · Migration 07 · Storage buckets + bucket-level RLS
-- Source of truth: docs/02_Architecture/Nook-ARCH-DESIGN-v1.0.md § 3.3 (deploy diagram)
-- + § 8.3 (PII / signed URL strategy) + buckets API per Supabase Storage docs.
--
-- Implicit dependency: the avatars RLS policies below call
--   storage.foldername(name)
-- which is a Supabase-managed helper in the `storage` schema
-- (EXISTS PUBLIC by default with Supabase images ≥ 2023). Running this
-- migration against a vanilla Postgres 15 without the Supabase storage
-- helpers will error. Verify before applying on non-Supabase targets:
--   SELECT proname FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
--    WHERE n.nspname = 'storage' AND proname = 'foldername';
--
-- Two buckets:
--   • avatars     — public read for display, write self-only
--                   (5 MB cap per SPEC § 4 file rule; 5 MB avatar variant)
--   • attachments — private; read restricted to same-conv members via message FK
--                   (50 MB cap matches ARCH § 7.2 budget)
--
-- Idempotent: ON CONFLICT (id) DO NOTHING + DO-block pg_policies check.

-- ====================================================================
-- 1. Insert buckets (idempotent via DO-block existence check)
--    Supabase cloud may already have default buckets; skip if present.
-- ====================================================================
do $$
begin
  if not exists (select 1 from storage.buckets where id = 'avatars') then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values (
      'avatars',
      'avatars',
      true,                                -- same-conv members fetch via signed URL; public for direct
      5 * 1024 * 1024,                     -- 5 MB
      array['image/png','image/jpeg','image/heic','image/webp']
    );
  end if;

  if not exists (select 1 from storage.buckets where id = 'attachments') then
    insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    values (
      'attachments',
      'attachments',
      false,                               -- strict RLS via message FK
      50 * 1024 * 1024,                    -- 50 MB
      array[
        'image/png','image/jpeg','image/heic','image/webp',
        'application/pdf','text/plain','text/markdown',
        'application/zip','application/msword',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      ]
    );
  end if;
end $$;

-- ====================================================================
-- 2. avatars bucket policies: read-public, write-self, delete-self
-- ====================================================================
do $$
begin
  -- Insert (upload): user can upload into their own folder (avatars/<auth.uid>/...)
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'avatars_insert_self'
  ) then
    create policy avatars_insert_self
      on storage.objects for insert
      to authenticated
      with check (
        bucket_id = 'avatars'
        -- Path convention enforced client-side: avatars/<user_id>/<file>
        and ((storage.foldername(name))[1] = auth.uid()::text)
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'avatars_update_self'
  ) then
    create policy avatars_update_self
      on storage.objects for update
      to authenticated
      using (
        bucket_id = 'avatars'
        and ((storage.foldername(name))[1] = auth.uid()::text)
      )
      with check (
        bucket_id = 'avatars'
        and ((storage.foldername(name))[1] = auth.uid()::text)
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'avatars_delete_self'
  ) then
    create policy avatars_delete_self
      on storage.objects for delete
      to authenticated
      using (
        bucket_id = 'avatars'
        and ((storage.foldername(name))[1] = auth.uid()::text)
      );
  end if;

  -- SELECT: bucket is `public=true`, so the implicit "anyone can read"
  -- policy generated by Supabase already covers this. We explicitly
  -- do NOT add a SELECT policy here to avoid double-granting.
  -- The signed-URL 3-min expiry strategy (ARCH § 8.4) handles
  -- sensitive avatar URLs by short-lifetime signing on demand.
end $$;

-- ====================================================================
-- 3. attachments bucket policies: read via conversation membership;
--    insert/delete only by uploader.
-- ====================================================================
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'attachments_read_via_message'
  ) then
    create policy attachments_read_via_message
      on storage.objects for select
      to authenticated
      using (
        bucket_id = 'attachments'
        and exists (
          select 1
          from public.messages m
          join public.conversation_members cm
            on cm.conversation_id = m.conversation_id
          join public.attachments a
            on a.message_id    = m.id
           and a.storage_path = storage.objects.name
          where cm.user_id  = auth.uid()
            and cm.left_at  is null
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'attachments_insert_self'
  ) then
    create policy attachments_insert_self
      on storage.objects for insert
      to authenticated
      with check (
        bucket_id = 'attachments'
        and owner = auth.uid()   -- Supabase storage: owner = uploader
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects'
      and policyname = 'attachments_delete_self'
  ) then
    create policy attachments_delete_self
      on storage.objects for delete
      to authenticated
      using (
        bucket_id = 'attachments'
        and owner = auth.uid()
      );
  end if;
end $$;

-- ====================================================================
-- End of migration 07 — 2 buckets + 5 storage.objects policies
-- ====================================================================
